name: custom_generator
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.4

dependencies:
  analyzer: ^6.5.0
  source_gen: ^1.5.0
  build: ^2.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
  # only for example
  build_runner: ^2.4.11
  

